<script setup lang="ts">
withDefaults(defineProps<{ mode: 'translation' | 'dubbing' | 'voices' }>(), {})
const target = ref('en')
const mediaName = ref('')
const voice = ref('preserve')
const draft = ref('')
function choose(event: Event) { mediaName.value = (event.target as HTMLInputElement).files?.[0]?.name ?? '' }
</script>
<template>
  <section class="page-intro"><p class="eyebrow">Language studio</p><h1>{{ mode === 'translation' ? 'Every word. A wider audience.' : mode === 'dubbing' ? 'A familiar voice. A new language.' : 'Find the right voice.' }}</h1><p>{{ mode === 'translation' ? 'Prepare a transcript for translation into another language.' : mode === 'dubbing' ? 'Prepare audio or video for a new language and voice.' : 'Explore the voice controls planned for your dubbing workspace.' }}</p></section>
  <div class="mb-6 flex items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm text-slate-500"><UiAppIcon name="clock" class="shrink-0" /><p>This feature is coming soon. You can explore the controls below; processing and output generation are not available yet.</p></div>
  <div class="grid items-start gap-6 xl:grid-cols-[1fr_320px]">
    <section class="surface p-6 sm:p-8">
      <div class="flex items-center gap-3"><span class="feature-icon" :data-accent="mode === 'translation' ? 'violet' : 'cyan'"><UiAppIcon :name="mode === 'translation' ? 'translate' : 'audio'" /></span><h2 class="text-xl font-semibold">{{ mode === 'translation' ? 'Source transcript' : mode === 'dubbing' ? 'Source media' : 'Voice settings' }}</h2></div>
      <template v-if="mode === 'translation'"><label class="mb-2 mt-6 block text-sm font-medium" for="translation-text">Transcript text</label><textarea id="translation-text" v-model="draft" rows="8" class="w-full rounded-xl border border-slate-200 bg-slate-50 p-4 text-base leading-relaxed" placeholder="Paste the transcript you want to translate…" /><NuxtLink class="mt-3 inline-flex items-center gap-2 text-sm text-indigo-600" to="/dashboard/transcriptions"><UiAppIcon name="folder" :size="16" />Find a transcript in your library</NuxtLink></template>
      <template v-else-if="mode === 'dubbing'"><label class="mt-6 flex cursor-pointer flex-col items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><UiAppIcon name="upload" :size="28" /><strong class="text-sm">{{ mediaName || 'Choose audio or video' }}</strong><span class="text-xs text-slate-500">Select a file to prepare your dubbing setup.</span><input type="file" accept="audio/*,video/*" class="sr-only" @change="choose"></label></template>
      <div class="mt-6 grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-medium" for="source-language">Source language</label><select id="source-language" class="min-h-11 w-full rounded-lg border border-slate-200 bg-white p-3 text-sm"><option>English</option><option>Yoruba</option><option>Igbo</option><option>Hausa</option><option>Nigerian Pidgin</option><option>Auto-detect</option></select></div><div><label class="mb-2 block text-sm font-medium" for="target-language">Output language</label><select id="target-language" v-model="target" class="min-h-11 w-full rounded-lg border border-slate-200 bg-white p-3 text-sm"><option value="en">English</option><option value="fr">French</option><option value="es">Spanish</option><option value="yo">Yoruba</option><option value="ig">Igbo</option><option value="ha">Hausa</option></select></div></div>
      <fieldset v-if="mode !== 'translation'" class="mt-6"><legend class="mb-3 text-sm font-medium">Voice preference</legend><label v-for="option in [{ value: 'preserve', name: 'Preserve original voice', copy: 'Keep the character of the source speaker.' }, { value: 'generate', name: 'Generate a natural voice', copy: 'Use a voice suited to the output language.' }]" :key="option.value" class="mb-3 flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-4"><input v-model="voice" type="radio" :value="option.value" name="voice" class="mt-1 accent-indigo-600"><span><strong class="block text-sm font-medium">{{ option.name }}</strong><small class="mt-1 block text-xs text-slate-500">{{ option.copy }}</small></span></label></fieldset>
      <button type="button" disabled class="button-primary mt-6 w-full opacity-50">{{ mode === 'translation' ? 'Translate transcript' : mode === 'dubbing' ? 'Generate dubbing' : 'Preview voice' }} · Coming soon</button>
    </section>
    <aside class="surface p-6"><h2 class="text-lg font-semibold">{{ mode === 'translation' ? 'Translated text' : 'Output preview' }}</h2><div class="mt-5 grid min-h-48 place-items-center rounded-xl border border-dashed border-slate-200 p-6 text-center"><div><UiAppIcon :name="mode === 'translation' ? 'translate' : 'audio'" :size="28" class="mx-auto text-slate-400" /><p class="mt-4 text-sm text-slate-500">Your output will appear here when processing becomes available.</p></div></div><p class="mt-4 text-xs leading-5 text-slate-500">Language and voice availability will depend on the connected provider.</p></aside>
  </div>
</template>
