export type LanguageOption = { name: string; codes: string[] }

export const transcriptionLanguages: LanguageOption[] = [
  { name: 'English', codes: ['en', 'en-US', 'en-AU', 'en-GB', 'en-IN', 'en-NZ'] },
  { name: 'Nigerian English', codes: ['en-NG'] }, { name: 'Nigerian Pidgin', codes: ['pcm'] },
  { name: 'Yorùbá', codes: ['yo'] }, { name: 'Igbo', codes: ['ig'] }, { name: 'Hausa', codes: ['ha'] },
  { name: 'Afrikaans', codes: ['af', 'af-ZA'] },
  { name: 'Arabic', codes: ['ar', 'ar-AE', 'ar-SA', 'ar-QA', 'ar-KW', 'ar-SY', 'ar-LB', 'ar-PS', 'ar-JO', 'ar-EG', 'ar-SD', 'ar-TD', 'ar-MA', 'ar-DZ', 'ar-TN', 'ar-IQ', 'ar-IR'] },
  { name: 'Armenian', codes: ['hy'] }, { name: 'Assamese', codes: ['as', 'as-IN'] }, { name: 'Belarusian', codes: ['be'] },
  { name: 'Bengali', codes: ['bn'] }, { name: 'Bosnian', codes: ['bs'] }, { name: 'Bulgarian', codes: ['bg'] }, { name: 'Catalan', codes: ['ca'] },
  { name: 'Chinese (Cantonese, Traditional)', codes: ['zh-HK'] },
  { name: 'Chinese (Mandarin, Simplified)', codes: ['zh', 'zh-CN', 'zh-Hans'] },
  { name: 'Chinese (Mandarin, Traditional)', codes: ['zh-TW', 'zh-Hant'] },
  { name: 'Croatian', codes: ['hr'] }, { name: 'Czech', codes: ['cs', 'cs-CZ'] }, { name: 'Danish', codes: ['da', 'da-DK'] },
  { name: 'Dutch', codes: ['nl'] },
  { name: 'Estonian', codes: ['et'] }, { name: 'Finnish', codes: ['fi'] }, { name: 'Flemish', codes: ['nl-BE'] },
  { name: 'French', codes: ['fr', 'fr-CA'] }, { name: 'Georgian', codes: ['ka', 'ka-GE'] }, { name: 'German', codes: ['de'] },
  { name: 'German (Switzerland)', codes: ['de-CH'] }, { name: 'Greek', codes: ['el'] }, { name: 'Gujarati', codes: ['gu', 'gu-IN'] },
  { name: 'Hebrew', codes: ['he'] }, { name: 'Hindi', codes: ['hi'] }, { name: 'Hungarian', codes: ['hu'] },
  { name: 'Indonesian', codes: ['id'] }, { name: 'Italian', codes: ['it'] }, { name: 'Japanese', codes: ['ja'] },
  { name: 'Kannada', codes: ['kn'] }, { name: 'Kazakh', codes: ['kk', 'kk-KZ'] }, { name: 'Korean', codes: ['ko', 'ko-KR'] },
  { name: 'Latvian', codes: ['lv'] }, { name: 'Lithuanian', codes: ['lt'] }, { name: 'Macedonian', codes: ['mk'] },
  { name: 'Malay', codes: ['ms'] }, { name: 'Marathi', codes: ['mr'] }, { name: 'Mongolian', codes: ['mn'] }, { name: 'Nepali', codes: ['ne'] },
  { name: 'Norwegian', codes: ['no'] }, { name: 'Pashto', codes: ['ps', 'ps-AF'] }, { name: 'Persian', codes: ['fa'] },
  { name: 'Polish', codes: ['pl'] }, { name: 'Portuguese', codes: ['pt', 'pt-BR', 'pt-PT'] }, { name: 'Punjabi', codes: ['pa', 'pa-IN'] },
  { name: 'Romanian', codes: ['ro'] }, { name: 'Russian', codes: ['ru'] }, { name: 'Serbian', codes: ['sr'] },
  { name: 'Slovak', codes: ['sk'] }, { name: 'Slovenian', codes: ['sl'] }, { name: 'Spanish', codes: ['es', 'es-419'] },
  { name: 'Swedish', codes: ['sv', 'sv-SE'] }, { name: 'Tagalog', codes: ['tl'] }, { name: 'Tamil', codes: ['ta'] },
  { name: 'Telugu', codes: ['te'] }, { name: 'Thai', codes: ['th', 'th-TH'] }, { name: 'Turkish', codes: ['tr', 'tr-TR'] },
  { name: 'Ukrainian', codes: ['uk'] }, { name: 'Urdu', codes: ['ur'] }, { name: 'Vietnamese', codes: ['vi'] },
]
