<script setup lang="ts">
import type { FolderTranscription } from '~/types/transcription'
import type { PrivacyDeletion } from '~/types/privacy'
import PrivacyDeleteAction from '~/components/privacy/PrivacyDeleteAction.vue'
defineProps<{ items: FolderTranscription[] }>()
const emit = defineEmits<{ select: [item: FolderTranscription]; deletion: [record: PrivacyDeletion] }>()
function duration(value: number | null) { if (value === null) return '—'; const seconds = Math.round(value); return `${Math.floor(seconds / 60)}m ${seconds % 60}s` }
function date(value: string | null) { return value ? new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : '—' }
</script>
<template>
  <div v-if="items.length" class="divide-y divide-slate-100 sm:hidden"><div v-for="item in items" :key="item.id" class="p-5"><button class="flex w-full gap-3 text-left" @click="emit('select', item)"><span class="grid size-11 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><UiAppIcon name="transcript" /></span><span class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ item.name }}</strong><small class="block truncate text-xs text-slate-500">{{ item.fileName }} · {{ duration(item.duration) }}</small></span><span class="status-badge" :class="`status-${item.status}`">{{ item.status }}</span></button><PrivacyDeleteAction class="mt-2" resource-type="transcription" :resource-id="item.id" scope="project" :name="item.name" label="Delete transcription" @accepted="emit('deletion', $event)" /></div></div>
  <div v-if="items.length" class="hidden overflow-x-auto sm:block"><table class="w-full min-w-[720px] text-left"><thead><tr class="border-b border-slate-200 bg-slate-50/80 text-xs font-semibold tracking-[.14em] text-slate-500"><th class="px-8 py-4">TRANSCRIPTION</th><th class="px-6 py-4">STATUS</th><th class="px-6 py-4">LENGTH</th><th class="px-8 py-4 text-right">CREATED</th><th class="px-4 py-4"><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="item in items" :key="item.id" class="cursor-pointer border-b border-slate-100 hover:bg-indigo-50/40" tabindex="0" @click="emit('select', item)" @keydown.enter="emit('select', item)"><td class="px-8 py-5"><p class="text-sm font-bold text-slate-800">{{ item.name }}</p><p class="mt-1 text-xs text-slate-500">{{ item.fileName }}</p></td><td class="px-6 py-5"><span class="status-badge" :class="`status-${item.status}`">{{ item.status }}</span></td><td class="px-6 py-5 text-sm text-slate-600">{{ duration(item.duration) }}</td><td class="px-8 py-5 text-right text-sm text-slate-500">{{ date(item.createdAt) }}</td><td class="px-4 py-5"><PrivacyDeleteAction resource-type="transcription" :resource-id="item.id" scope="project" :name="item.name" label="Delete" @accepted="emit('deletion', $event)" /></td></tr></tbody></table></div>
  <div v-else class="grid min-h-72 place-items-center p-12 text-center"><div><span class="mx-auto grid size-14 place-items-center rounded-2xl bg-violet-50 text-2xl text-violet-600"><UiAppIcon name="transcript" /></span><h3 class="mt-5 text-2xl font-semibold">This folder is empty</h3><p class="mt-2 text-sm text-slate-500">Choose this folder when starting a transcription.</p></div></div>
</template>
